#!/bin/bash
mkdir src/trie
mkdir src/cityhash
cp ../../src/threading.h src/
cp ../../src/trie/* src/trie/
cp ../../src/cityhash/* src/cityhash/
swig -php -c++ src/trie/51Degrees.i
g++ `php-config --includes` -fpic -Wno-write-strings -c src/trie/51Degrees_wrap.cpp src/trie/Match.cpp src/trie/Provider.cpp src/trie/51Degrees.c src/cityhash/city.c
g++ -shared *.o -o FiftyOneDegreesTrieV3.so
rm *.o
mkdir module
mv FiftyOneDegreesTrieV3.so module/
mv src/trie/FiftyOneDegreesTrieV3.php module/
