#!/bin/bash
cd ..
if [ ! -d 51Degrees_module ] ; then
	mkdir 51Degrees_module
fi
cp src/* 51Degrees_module/
if [ ! -d 51Degrees_module/src ] ; then
	mkdir 51Degrees_module/src
fi
if [ ! -d 51Degrees_module/src/pattern ] ; then
	mkdir 51Degrees_module/src/pattern
fi
if [ ! -d 51Degrees_module/src/cityhash ] ; then
	mkdir 51Degrees_module/src/cityhash
fi
cp ../src/pattern/51Degrees.c 51Degrees_module/src/pattern/
cp ../src/pattern/51Degrees.h 51Degrees_module/src/pattern/
cp -r ../src/cityhash/ 51Degrees_module/src/
cp ../src/threading.h 51Degrees_module/src/

set -o nounset
set -o errexit

DIR=$(pwd)
BUILDDIR=$DIR/build
NGINX_DIR=nginx
NGINX_VERSION=1.4.7

rm -rf build vendor
if [ ! -d $BUILDDIR ]; then
	mkdir $BUILDDIR > /dev/null 2>&1
	mkdir $BUILDDIR/$NGINX_DIR > /dev/null 2>&1
fi

if [ ! -d "vendor" ]; then
	mkdir vendor > /dev/null 2>&1
fi
if [ ! -d "vendor/nginx-$NGINX_VERSION" ]; then
	pushd vendor > /dev/null 2>&1
	curl -s -L -O "http://nginx.org/download/nginx-$NGINX_VERSION.tar.gz"
	tar xzf "nginx-$NGINX_VERSION.tar.gz"
	popd > /dev/null 2>&1
else
	printf "NGINX already downloaded\n"
fi
cd CodeBlocks
