/**
 * This Source Code Form is copyright of 51Degrees Mobile Experts Limited.
 * Copyright (c) 2015 51Degrees Mobile Experts Limited, 5 Charlotte Close,
 * Caversham, Reading, Berkshire, United Kingdom RG4 7BY
 * 
 * This Source Code Form is the subject of the following patent
 * applications, owned by 51Degrees Mobile Experts Limited of 5 Charlotte
 * Close, Caversham, Reading, Berkshire, United Kingdom RG4 7BY:
 * European Patent Application No. 13192291.6; and
 * United States Patent Application Nos. 14/085,223 and 14/085,301.
 * 
 * This Source Code Form is subject to the terms of the Mozilla Public
 * License, v. 2.0.
 * 
 * If a copy of the MPL was not distributed with this file, You can obtain
 * one at http://mozilla.org/MPL/2.0/.
 * 
 * This Source Code Form is "Incompatible With Secondary Licenses", as
 * defined by the Mozilla Public License, v. 2.0.
 */

/*
<tutorial>
Offline processing example of using 51Degrees device detection. The example 
shows how to:
<ol>
    <li> Initialise detector with path to the 51Degrees device data file and 
    a list of properties.
    <p><code>
        string properties = "IsMobile";
        string fileName = args[0];
        Provider provider = new Provider(FileName, properties);
    </code></p>
    <li> Open an input file with a list of User-Agents, and an output file,
    <p><code>
        StreamReader fin = new StreamReader(inputFile);
        StreamWriter fout = new StreamWriter(outputFile);
    </code></p>
    <li> Write a header to the output file with the property names in '|'
    separated CSV format ('|' sepparated because some User-Agents contain
    commas)
    <p><code>
        fout.Write("User-Agent");<br>
        for (i = 0; i < properties.Count(); i++ )<br>
        {<br>
            fout.Write("|" + properties[i]);<br>
        }<br>
        fout.Write("\n");
    </code></p>
    <li> For the first 20 User-Agents in the input file,perform a match, then
    write the User-Agent along with the values for chosen properties to
    the output CSV file.
    <p><code>
        for (i = 1; i < 20; i++ )
        {
            userAgent = fin.ReadLine();
            using(match = provider.getMatch(userAgent)) 
            {
                Assert.IsNotNull(match);
                fout.Write(userAgent);
                for (j = 0; j < properties.Count(); j++)
                {
                    fout.Write("|" + match.getValue(properties[j]));
                }
                fout.Write("\n");
            }
        }
    </code></p>
    <li> Dispose of the Provider releasing the resources.
    <p><code>
        provider.Dispose();
    </code></p>
</ol>
<p>
    This tutorial assumes you are building this example using Visual Studio. 
    You should supply path to the 51Degrees device data file that you wish to 
    use as a command line argument.
</p>
<p>
    By default the API is distributed with Lite data which is free to use for 
    both the non-commercial and commercial purposes. Lite data file contains 
    over 60 properties. For more properties like DeviceType, PriceBand and 
    HardwareVendor check out the Premium and Enterprise data files:
    https://51degrees.com/compare-data-options
</p>
<p>
    Passing a list of properties to the provider constructor limits the number 
    of properties in the dataset the provider wraps to only the chosen 
    properties. Not providing a list or providing an empty list will cause the 
    dataset to be created with all available properties:
    <br /><code>
        Provider provider = new Provider(fileName, "");
        Provider provider = new Provider(fileName);
    </code>
</p>
<p>
    This code works with the assembly generated by SWIG from the 51Degrees C 
    source files. The garbage collection does not apply to the SWIG-generated 
    code. You should always use the Dispose() methods on any objects that 
    originate from the unmanaged code.
</p>
<p>
    Match retrieves the workset from the pool of worksets and not disposing 
    of the Match objects will eventually exhaust the pool and cause the 
    program to stall as it waits for the free workset. We recommend you either 
    use Match object in the context of a using statement or within the try 
    finally block where the match is disposed of if not null.
</p>
<p>
    Provider wraps the dataset which is the data file loaded into memory and 
    ready to be used through the methods exposed by the Provider. Failing to 
    dispose of the provider when it is no longer required means the memory 
    allocated for the provider, cache, pool and the dataset will never be 
    released.
</p>
</tutorial>
*/
using Microsoft.VisualStudio.TestTools.UnitTesting;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using FiftyOne.Mobile.Detection.Provider.Interop.Pattern;
using System.IO;

namespace FiftyOne.Example.Illustration.CSharp.OfflineProcessing
{
    public class Program
    {
        // Snippet Start
        /// <summary>
        /// Runs the program.
        /// </summary>
        /// <param name="fileName">
        /// Path to the 51Degrees device data file.
        /// </param>
        /// <param name="inputFile">
        /// Path to the input data file containing User-Agents to process.
        /// </param>
        public static void Run(string fileName, string inputFile)
        {
            int i, j;
            // Where to store processed User-Agents.
            string outputFile = "OfflineProcessingOutput.csv";
            string userAgent;
            Match match;
            string propertiesList = "IsMobile,PlatformName,PlatformVersion";

            Provider provider = new Provider(fileName, propertiesList);

            // Fetched available properties as a VectorString.
            VectorString properties = provider.getAvailableProperties();

            // Opens input and output files.
            StreamReader fin = new StreamReader(inputFile);
            StreamWriter fout = new StreamWriter(outputFile);

            Console.WriteLine("Starting Offline Processing Example.");

            // Print CSV headers to output file.
            fout.Write("User-Agent");
            for (i = 0; i < properties.Count(); i++ )
            {
                fout.Write("|" + properties[i]);
            }
            fout.Write("\n");

            // Carries out match for first 20 User-Agents and prints results to
            // output file.
            for (i = 1; i < 20; i++ )
            {
                userAgent = fin.ReadLine();
                using(match = provider.getMatch(userAgent)) 
                {
                    Assert.IsNotNull(match);
                    fout.Write(userAgent);
                    for (j = 0; j < properties.Count(); j++)
                    {
                        fout.Write("|" + match.getValue(properties[j]));
                    }
                    fout.Write("\n");
                }
            }

            fin.Close();
            fout.Close();

            Console.WriteLine("Output Written to " + outputFile);

            // At the end of the program dispose of the data file to 
            // deallocate memory.
            provider.Dispose();
        }
        // Snippet End

        static void Main(string[] args)
        {
            string fileName = args.Length > 0 ? args[0] : 
                "../../../../../../data/51Degrees-LiteV3.2.dat";
            string inputFile = args.Length > 1 ? args[1] : 
                "../../../../../../data/20000 User Agents.csv";
            Run(fileName, inputFile);

            // Waits for a character to be pressed.
            Console.ReadKey();
        }
    }
}
