#!/bin/bash

mkdir src
mkdir src/pattern
mkdir src/cityhash
cp -r ../src/pattern/ 51Degrees_module/src
cp -r ../src/cityhash/ 51Degrees_module/src
cp ../src/threading.h 51Degrees_module/src/
pushd "vendor"
pushd "nginx-1.4.7"
CFLAGS="-g -O0" ./configure           \
    --with-debug                      \
    --prefix=$(pwd)/../../build/nginx \
    --conf-path=conf/nginx.conf       \
    --error-log-path=logs/error.log   \
    --http-log-path=logs/access.log   \
    --with-ld-opt="-lm"  \
    --add-module=../../51Degrees_module
make install
popd
popd
