#!/bin/bash
mkdir 51Degrees_module
cp src/* 51Degrees_module/
mkdir 51Degrees_module/src
mkdir 51Degrees_module/src/pattern
mkdir 51Degrees_module/src/cityhash
cp ../src/pattern/51Degrees.c 51Degrees_module/src/pattern/
cp ../src/pattern/51Degrees.h 51Degrees_module/src/pattern/
cp -r ../src/cityhash/ 51Degrees_module/src/
cp ../src/threading.* 51Degrees_module/src/
echo "51Degrees module files copied to 51Degrees_module"
