[package]
name = "fiftyonedegrees-sys"
version = "0.1.0"
edition = "2018"
publish = false

[features]
browser-name-enum = []
browser-name-enum-mode = []
platform-name-enum = []
trie = []
pattern = []

[dependencies]
libc = "0.2.64"

[build-dependencies]
cc = "1.0.46"
